name: Python checks

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run checks in Docker
        run: docker compose run --rm check